### ISSUE TITLE
Allow offline level import/export

### ISSUE THREAD

**Issue by Sturwandan** [lostmsu/RoboZZle-Droid#3]
Hello. Suppose there are two android devices. One has internet access and other doesn't. It would be nice to have a way to load the levels into the device without internet. For that I see two options:

a) The online device has RoboZZle-Droid saved the level data somewhere. So it could be copied and then transferred by bluetooth or via USB-otg flash or whatever. This scenario would work if I knew where the data is stored. I get a feeling that it's in a hidden partition which is inaccessible without root. Or at least it's not obvious.

b) There is some URL allowing to download all the levels directly and then import it offline. 

So can you please implement offline level importing, or point out how it's performed if it's already doable?

**Comment by lostmsu** [comment]
This is a very niche feature request. I don't think I will be implementing that feature.

I suppose your best bet is to use one of the Android backup apps, back up RoboZZle-Droid on the device with the puzzles and restore on the device without.

If you want to try your luck with code, you should start with https://github.com/lostmsu/RoboZZle-Droid/blob/master/src/com/team242/robozzle/RobozzleOffline.java , which implements the SQLite database IO. A PR would be welcome.

**Comment by Sturwandan** [comment]
@lostmsu 
I am thinking, would it be possible to export/import the program at least? In the browser version it's done by copying a piece of URL after `program=` part. Sometimes after I have done a solution, I want to try a completely different approach, but I do not want to lose the progress if it doesn't work.
